// (c) 2018 ITOMIG GmbH

Dict::Add('DE DE', 'German', 'Deutsch', array(
	// Dictionary entries go here
	'Menu:Templates' => 'Vorlagen',
	'Menu:Templates+' => 'Vorlagen für Objekt-Erzeugungs-Formulare',
	'Templates:UserData' => 'Zusatzdaten',
	'Templates:UserData-Source' => 'Erzeugt aus Vorlage %1$s',

	'Templates:PreviewTab:Title' => 'Vorschau',
	'Templates:PreviewTab:FormFields' => 'Vorschau-Formular',
	'Templates:PreviewTab:HiddenFields' => 'Versteckte Felder',

	'Class:Template' => 'Vorlage',
	'Class:Template+' => 'Vorlage für Objekterzeugung aus dem Portal',
	'Class:Template/Attribute:name' => 'Name',
	'Class:Template/Attribute:name+' => 'Interner Name',
	'Class:Template/Attribute:label' => 'Beschriftung',
	'Class:Template/Attribute:label+' => 'Beschriftung, die im Formular angezeigt wird',
	'Class:Template/Attribute:description' => 'Beschreibung',
	'Class:Template/Attribute:description+' => 'Beschreibung, die im Formular verwendet wird',
	'Class:Template/Attribute:field_list' => 'Felder',
	'Class:Template/Attribute:field_list+' => '',

	'Class:TemplateField' => 'Feld',
	'Class:TemplateField+' => '',
	'Class:TemplateField/Attribute:template_id' => 'Vorlage',
	'Class:TemplateField/Attribute:template_id+' => '',
	'Class:TemplateField/Attribute:template_id_finalclass_recall' => 'Typ',
	'Class:TemplateField/Attribute:template_id_finalclass_recall+' => '',
	'Class:TemplateField/Attribute:code' => 'Code',
	'Class:TemplateField/Attribute:code+' => 'Attributs-Code oder beliebiger Wert',
	'Class:TemplateField/Attribute:label' => 'Beschriftung',
	'Class:TemplateField/Attribute:label+' => 'Wird den Endbenutzern angezeigt',
	'Class:TemplateField/Attribute:order' => 'Reihenfolge',
	'Class:TemplateField/Attribute:order+' => 'Position im Formular',
	'Class:TemplateField/Attribute:mandatory' => 'Pflichtfeld',
	'Class:TemplateField/Attribute:mandatory+' => '',
	'Class:TemplateField/Attribute:input_type' => 'Eingabefeldtyp',
	'Class:TemplateField/Attribute:input_type+' => '',
	'Class:TemplateField/Attribute:input_type/Value:text' => 'Textfeld',
	'Class:TemplateField/Attribute:input_type/Value:text+' => '',
	'Class:TemplateField/Attribute:input_type/Value:text_area' => 'Textbereich',
	'Class:TemplateField/Attribute:input_type/Value:text_area+' => '',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list' => 'Drop-down-Liste',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list+' => '',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons' => 'Liste',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date' => 'Datum',
	'Class:TemplateField/Attribute:input_type/Value:date+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time' => 'Dateum mit Uhreit',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time+' => '',
	'Class:TemplateField/Attribute:input_type/Value:duration' => 'Dauer',
	'Class:TemplateField/Attribute:input_type/Value:duration+' => '',
	'Class:TemplateField/Attribute:input_type/Value:read_only' => 'Read-Only',
	'Class:TemplateField/Attribute:input_type/Value:read_only+' => '',
	'Class:TemplateField/Attribute:input_type/Value:hidden' => 'Versteckt',
	'Class:TemplateField/Attribute:input_type/Value:hidden+' => '',
	'Class:TemplateField/Attribute:values' => 'Werte (OQL oder CSV)',
	'Class:TemplateField/Attribute:values+' => '"SELECT myClass WHERE name LIKE \'foo\'" or "val1,val2,..."',
	'Class:TemplateField/Attribute:initial_value' => 'Default-Wert',
	'Class:TemplateField/Attribute:initial_value+' => '',
	'Class:TemplateField/Attribute:format' => 'Format',
	'Class:TemplateField/Attribute:format+' => 'Regulärer Ausdruck',
));
?>
