<?php
// Copyright (C) 2010-2016 Combodo SARL

Dict::Add('ES CR', 'Spanish', 'Español, Castellano', array(
	// Dictionary entries go here
	'Menu:Templates' => 'Plantillas',
	'Menu:Templates+' => 'Plantillas para la creación de formas de objetos',
	'Templates:UserData' => 'Datos Extra',
	'Templates:Need' => 'Necesario',

	'Templates:PreviewTab:Title' => 'Vista Preliminar',
	'Templates:PreviewTab:FormFields' => 'Forma Falsa',
	'Templates:PreviewTab:HiddenFields' => 'Campos Ocultos',

	'Class:Template' => 'Plantilla',
	'Class:Template+' => 'Plantilla para crear objetos desde el Portal',
	'Class:Template/Attribute:name' => 'Nombre',
	'Class:Template/Attribute:name+' => 'Nombre Interno',
	'Class:Template/Attribute:label' => 'Etiqueta',
	'Class:Template/Attribute:label+' => 'Etiqueta usada en la Forma',
	'Class:Template/Attribute:description' => 'Descripción',
	'Class:Template/Attribute:description+' => 'Descripción usada en la forma',
	'Class:Template/Attribute:field_list' => 'Campos',
	'Class:Template/Attribute:field_list+' => '',

	'Class:TemplateField' => 'Campo',
	'Class:TemplateField+' => '',
	'Class:TemplateField/Attribute:template_id' => 'Plantilla',
	'Class:TemplateField/Attribute:template_id+' => '',
	'Class:TemplateField/Attribute:template_id_finalclass_recall' => 'Tipo',
	'Class:TemplateField/Attribute:template_id_finalclass_recall+' => '',
	'Class:TemplateField/Attribute:code' => 'Código',
	'Class:TemplateField/Attribute:code+' => 'Código de Atributo o algún valor',
	'Class:TemplateField/Attribute:label' => 'Etiqueta',
	'Class:TemplateField/Attribute:label+' => 'Desplegada a usuario final',
	'Class:TemplateField/Attribute:order' => 'Orden',
	'Class:TemplateField/Attribute:order+' => 'Posición en la forma',
	'Class:TemplateField/Attribute:mandatory' => 'Mandatorio',
	'Class:TemplateField/Attribute:mandatory+' => '',
	'Class:TemplateField/Attribute:input_type' => 'Tipo de Entrada',
	'Class:TemplateField/Attribute:input_type+' => '',
	'Class:TemplateField/Attribute:input_type/Value:text' => 'Texto',
	'Class:TemplateField/Attribute:input_type/Value:text+' => '',
	'Class:TemplateField/Attribute:input_type/Value:text_area' => 'Área de Texto',
	'Class:TemplateField/Attribute:input_type/Value:text_area+' => '',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list' => 'Lista Drop-down',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list+' => '',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons' => 'Lista',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date' => 'Fecha',
	'Class:TemplateField/Attribute:input_type/Value:date+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time' => 'Fecha y hora',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time+' => '',
	'Class:TemplateField/Attribute:input_type/Value:duration' => 'Duración',
	'Class:TemplateField/Attribute:input_type/Value:duration+' => '',
	'Class:TemplateField/Attribute:input_type/Value:read_only' => 'Sólo Lectura',
	'Class:TemplateField/Attribute:input_type/Value:read_only+' => '',
	'Class:TemplateField/Attribute:input_type/Value:hidden' => 'Oculto',
	'Class:TemplateField/Attribute:input_type/Value:hidden+' => '',
	'Class:TemplateField/Attribute:values' => 'Valores (OQL o CSV)',
	'Class:TemplateField/Attribute:values+' => '"SELECT myClass WHERE name LIKE \'foo\'" or "val1,val2,..."',
	'Class:TemplateField/Attribute:initial_value' => 'Valor Inicial',
	'Class:TemplateField/Attribute:initial_value+' => '',
	'Class:TemplateField/Attribute:format' => 'Formato',
	'Class:TemplateField/Attribute:format+' => 'Expresión Regular',
));
