<?php
// Copyright (C) 2010-2018 Combodo SARL

Dict::Add('PT BR', 'Brazilian', 'Brazilian', array(
	// Dictionary entries go here
	'Menu:Templates' => 'Modelos',
	'Menu:Templates+' => 'Modelos para formulários de criação de objetos',
	'Templates:UserData' => 'Dados extras',
	'Templates:Need' => 'Necessidade',

	'Templates:PreviewTab:Title' => 'Anterior',
	'Templates:PreviewTab:FormFields' => 'Formulário falso',
	'Templates:PreviewTab:HiddenFields' => 'Campos ocultos',

	'Class:Template' => 'Modelo',
	'Class:Template+' => 'Modelo para criar objetos no Portal',
	'Class:Template/Attribute:name' => 'Nome',
	'Class:Template/Attribute:name+' => 'Nome interno',
	'Class:Template/Attribute:label' => 'Rótulo',
	'Class:Template/Attribute:label+' => 'Rótulo usado no formulário',
	'Class:Template/Attribute:description' => 'Descrição',
	'Class:Template/Attribute:description+' => 'Descrição usada no formulário',
	'Class:Template/Attribute:field_list' => 'Campos',
	'Class:Template/Attribute:field_list+' => '',

	'Class:TemplateField' => 'Campo',
	'Class:TemplateField+' => '',
	'Class:TemplateField/Attribute:template_id' => 'Modelo',
	'Class:TemplateField/Attribute:template_id+' => '',
	'Class:TemplateField/Attribute:template_id_finalclass_recall' => 'Tipo',
	'Class:TemplateField/Attribute:template_id_finalclass_recall+' => '',
	'Class:TemplateField/Attribute:code' => 'Código',
	'Class:TemplateField/Attribute:code+' => 'Código do atributo ou qualquer valor',
	'Class:TemplateField/Attribute:label' => 'Rótulo',
	'Class:TemplateField/Attribute:label+' => 'Exibido para os usuários finais',
	'Class:TemplateField/Attribute:order' => 'Ordem',
	'Class:TemplateField/Attribute:order+' => 'Posição no formulário',
	'Class:TemplateField/Attribute:mandatory' => 'Obrigatório',
	'Class:TemplateField/Attribute:mandatory+' => '',
	'Class:TemplateField/Attribute:input_type' => 'Tipo de entrada',
	'Class:TemplateField/Attribute:input_type+' => '',
	'Class:TemplateField/Attribute:input_type/Value:text' => 'Texto',
	'Class:TemplateField/Attribute:input_type/Value:text+' => '',
	'Class:TemplateField/Attribute:input_type/Value:text_area' => 'Área de texto',
	'Class:TemplateField/Attribute:input_type/Value:text_area+' => '',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list' => 'Lista suspensa',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list+' => '',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons' => 'Lista',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date' => 'Data',
	'Class:TemplateField/Attribute:input_type/Value:date+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time' => 'Data e hora',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time+' => '',
	'Class:TemplateField/Attribute:input_type/Value:duration' => 'Duração',
	'Class:TemplateField/Attribute:input_type/Value:duration+' => '',
	'Class:TemplateField/Attribute:input_type/Value:read_only' => 'Somente leitura',
	'Class:TemplateField/Attribute:input_type/Value:read_only+' => '',
	'Class:TemplateField/Attribute:input_type/Value:hidden' => 'Oculto',
	'Class:TemplateField/Attribute:input_type/Value:hidden+' => '',
	'Class:TemplateField/Attribute:values' => 'Valores (OQL ou CSV)',
	'Class:TemplateField/Attribute:values+' => '"SELECT myClass WHERE name LIKE \'foo\'" or "val1,val2,..."',
	'Class:TemplateField/Attribute:initial_value' => 'Valor inicial',
	'Class:TemplateField/Attribute:initial_value+' => '',
	'Class:TemplateField/Attribute:format' => 'Formato',
	'Class:TemplateField/Attribute:format+' => 'Expressão regular',
));
